# Generated by Django 6.0.4 on 2026-05-02 18:02

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram')], max_length=20, verbose_name='platform')),
                ('platform_user_id', models.CharField(help_text='User ID from the platform (Discord user ID or Telegram user ID)', max_length=255, verbose_name='platform user ID')),
                ('platform_username', models.CharField(max_length=255, verbose_name='platform username')),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField(help_text='OAuth access token (encrypted)', verbose_name='access token')),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='OAuth refresh token (encrypted)', null=True, verbose_name='refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True, verbose_name='token expires at')),
                ('bot_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Telegram bot token (encrypted)', null=True, verbose_name='bot token')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=20, verbose_name='status')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last time channels were synced', null=True, verbose_name='last sync')),
                ('error_message', models.TextField(blank=True, help_text='Last error message if status is error', null=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Connection',
                'verbose_name_plural': 'Platform Connections',
                'db_table': 'platform_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(help_text='Platform-specific channel/server ID', max_length=255, verbose_name='channel ID')),
                ('channel_name', models.CharField(max_length=255, verbose_name='channel name')),
                ('channel_type', models.CharField(choices=[('discord_server', 'Discord Server'), ('discord_channel', 'Discord Channel'), ('telegram_group', 'Telegram Group'), ('telegram_channel', 'Telegram Channel')], max_length=20, verbose_name='channel type')),
                ('member_count', models.IntegerField(blank=True, help_text='Number of members in the channel/server', null=True, verbose_name='member count')),
                ('icon_url', models.URLField(blank=True, help_text='URL to channel/server icon', max_length=500, null=True, verbose_name='icon URL')),
                ('description', models.TextField(blank=True, help_text='Channel/server description', null=True, verbose_name='description')),
                ('can_read_messages', models.BooleanField(default=False, help_text='Whether bot has permission to read messages', verbose_name='can read messages')),
                ('can_read_history', models.BooleanField(default=False, help_text='Whether bot can read message history', verbose_name='can read history')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this channel is still accessible', verbose_name='is active')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last time channel data was synced', null=True, verbose_name='last synced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='integrations.platformconnection')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'db_table': 'channels',
                'ordering': ['channel_name'],
            },
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['user', 'platform'], name='platform_co_user_id_de60f0_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['status'], name='platform_co_status_763689_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformconnection',
            unique_together={('user', 'platform', 'platform_user_id')},
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['connection', 'is_active'], name='channels_connect_88bf27_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_type'], name='channels_channel_2bceca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('connection', 'channel_id')},
        ),
    ]
