# Generated by Django 6.0.4 on 2026-05-02 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether monitoring is currently active', verbose_name='is active')),
                ('fetch_frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('EVERY_6_HOURS', 'Every 6 Hours'), ('DAILY', 'Daily')], default='HOURLY', help_text='How often to fetch messages from this channel', max_length=20, verbose_name='fetch frequency')),
                ('monitoring_start_date', models.DateField(auto_now_add=True, help_text='Date when monitoring started', verbose_name='monitoring start date')),
                ('monitoring_end_date', models.DateField(blank=True, help_text='Date when monitoring should end (optional)', null=True, verbose_name='monitoring end date')),
                ('last_fetched_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful message fetch', null=True, verbose_name='last fetched at')),
                ('message_count', models.IntegerField(default=0, help_text='Total number of messages fetched (denormalized)', verbose_name='message count')),
                ('fetch_success_count', models.IntegerField(default=0, help_text='Number of successful fetches', verbose_name='fetch success count')),
                ('fetch_failure_count', models.IntegerField(default=0, help_text='Number of failed fetches', verbose_name='fetch failure count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(help_text='Channel being monitored', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_configs', to='integrations.channel')),
                ('user', models.ForeignKey(help_text='User who owns this monitoring configuration', on_delete=django.db.models.deletion.CASCADE, related_name='monitored_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitored Channel',
                'verbose_name_plural': 'Monitored Channels',
                'db_table': 'monitored_channels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('FETCH', 'Fetch Messages'), ('SUMMARIZE', 'Generate Summary')], help_text='Type of task to schedule', max_length=20, verbose_name='schedule type')),
                ('cron_expression', models.CharField(help_text='Cron expression for scheduling (e.g., "0 * * * *" for hourly)', max_length=100, verbose_name='cron expression')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active', verbose_name='is active')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this schedule last executed', null=True, verbose_name='last run at')),
                ('next_run_at', models.DateTimeField(help_text='When this schedule should run next', verbose_name='next run at')),
                ('run_count', models.IntegerField(default=0, help_text='Total number of times this schedule has run', verbose_name='run count')),
                ('failure_count', models.IntegerField(default=0, help_text='Number of failed executions', verbose_name='failure count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitored_channel', models.ForeignKey(help_text='Monitored channel this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='monitoring.monitoredchannel')),
            ],
            options={
                'verbose_name': 'Monitoring Schedule',
                'verbose_name_plural': 'Monitoring Schedules',
                'db_table': 'monitoring_schedules',
                'ordering': ['next_run_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoredchannel',
            index=models.Index(fields=['user', 'is_active'], name='monitored_c_user_id_854eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoredchannel',
            index=models.Index(fields=['is_active'], name='monitored_c_is_acti_4fa45b_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoredchannel',
            index=models.Index(fields=['last_fetched_at'], name='monitored_c_last_fe_1e902a_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoredchannel',
            index=models.Index(fields=['fetch_frequency'], name='monitored_c_fetch_f_401a7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoredchannel',
            unique_together={('user', 'channel')},
        ),
        migrations.AddIndex(
            model_name='monitoringschedule',
            index=models.Index(fields=['next_run_at', 'is_active'], name='monitoring__next_ru_c9da47_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringschedule',
            index=models.Index(fields=['schedule_type'], name='monitoring__schedul_d24773_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringschedule',
            index=models.Index(fields=['monitored_channel', 'schedule_type'], name='monitoring__monitor_f6e6d1_idx'),
        ),
    ]
